trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildVersion: 'latest'